In [1]:
import numpy as np

In [3]:
# 验证第n组左右奇异向量与奇异值满足自洽方程

dim = 4
M = np.random.randn(dim, dim)
U, S, V = np.linalg.svd(M)

n = 2  # 检查第n个组左右奇异向量

u = U[:, n]
s = S[n]
v = V[n, :]

print('For the ' + str(n) + '-th left and right singular vectors and singular values, ')
print('s * v = ')
print(s * v)
print('u * M = ')
print(u.dot(M))

For the 2-th left and right singular vectors and singular values, 
s * v = 
[-0.13491279  0.00735695  0.23851439  0.29752861]
u * M = 
[-0.13491279  0.00735695  0.23851439  0.29752861]


In [4]:
# 最大奇异值及对应的左右奇异向量的迭代算法
# 假设矩阵M为实矩阵

def svd0(mat, it_time=100, tol=1e-15):
    """
    :param mat: input matrix (assume to be real)
    :param it_time: max iteration time
    :param tol: tolerance of error
    :return u: the dominant left singular vector
    :return s: the dominant singular value
    :return v: the dominant right singular vector
    """
    dim0, dim1 = mat.shape
    # 随机初始化奇异向量
    u, v = np.random.randn(dim0, ), np.random.randn(dim1, )
    # 归一化初始向量
    u, v = u/np.linalg.norm(u), v/np.linalg.norm(v)
    s = 1

    for t in range(it_time):
        # 更新v和s
        v1 = u.dot(mat)
        s1 = np.linalg.norm(v1)
        v1 /= s1
        # 更新u和s
        u1 = mat.dot(v1)
        s1 = np.linalg.norm(u1)
        u1 /= s1
        # 计算收敛程度
        conv = np.linalg.norm(u - u1) / dim0 + np.linalg.norm(v - v1) / dim1
        u, s, v = u1, s1, v1
        # 判断是否跳出循环
        if conv < tol:
            break
    return u, s, v

In [5]:
# 验证上面算法的正确性
# 利用numpy库中的svd函数计算最大奇异值及对应的奇异向量
M = np.random.randn(3, 5)
U, S, V = np.linalg.svd(M)
u0, s0, v0 = U[:, 0], S[0], V[0, :]

# 利用上述算法计算最大奇异值及对应的奇异向量
u1, s1, v1 = svd0(M)

print('The dominant left singular vector by svd = ')
print(u0)
print('The dominant left singular vector by the iterative algorithm = ')
print(u1)

print('\n The dominant right singular vector by svd = ')
print(v0)
print('The dominant right singular vector by the iterative algorithm = ')
print(v1)

print('\n The dominant singular value by svd = ')
print(s0)
print('The dominant singular value by the iterative algorithm = ')
print(s1)

The dominant left singular vector by svd = 
[-0.20401265 -0.35018626  0.91419277]
The dominant left singular vector by the iterative algorithm = 
[ 0.20401265  0.35018626 -0.91419277]

 The dominant right singular vector by svd = 
[ 0.03966432 -0.09903221  0.97139136 -0.00925571 -0.21197294]
The dominant right singular vector by the iterative algorithm = 
[-0.03966432  0.09903221 -0.97139136  0.00925571  0.21197294]

 The dominant singular value by svd = 
2.51012165731717
The dominant singular value by the iterative algorithm = 
2.5101216573171703
